### ISSUE TITLE
Music score reader (without sound)

### ISSUE THREAD

**Issue by graciano** [graciano/tanana#1]
Read a music xml file and create the music score.
Then, make a player using MIDI events or something like that. The player is *not* to execute the audio, but to make a cursor that jumps from note to note, to be a guide for the student.

**Comment by graciano** [comment]
osmd has a system for that, I just have to use it. 

Look in the [demo](https://opensheetmusicdisplay.github.io/demo/) and click on 'next' button

**Comment by graciano** [comment]
When [this issue from osmd](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/108) solves, see if this can be considered done

**Comment by sebastianhaas** [comment]
Hey, just in case you haven't seen it, [opensheetmusicdisplay#108](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/108) is resolved. :) Keep up the awesome work and let me know if there is something I can do on OSMD-side to help.

**Comment by graciano** [comment]
@sebastianhaas I saw it in the weekend. I don't have the time yet to check it out. Thank you for all. Your library saved this project :)
![image](https://cloud.githubusercontent.com/assets/3246681/24866542/ca466b24-1de0-11e7-869b-77e82475ae71.png)

**Comment by graciano** [comment]
In  e02223a it makes this almost done. The remaining task is for the cursor to trigger a scroll down event in the window.

**Comment by sebastianhaas** [comment]
I'm pretty sure we'd like to see some scrolling logic as well in the library's core. So if you'd like to join forces on the matter, any help would be more than welcome. Just in case.

**Comment by graciano** [comment]
@sebastianhaas will check this by the end of the month. I'll have to learn type script first :)

**Comment by graciano** [comment]
still not reading music xml hello world, but the rest of the scores are acceptable

**Comment by sebastianhaas** [comment]
Would you be willing to open a ticket at https://github.com/opensheetmusicdisplay/opensheetmusicdisplay so we can fix this for you?
